baseURL = "https://links.iamdejan.my.id"
languageCode = "en"
defaultContentLanguage = "en"
theme = "lynx"

[params.author]
  name = "Giovanni Dejan"
  headline = "An overrated developer"
  image = "https://avatars.githubusercontent.com/u/15686093?v=4"

  links = [
    { link = {href = "https://iamdejan.my.id", text = "My Main Website"}},
    { link = {href = "https://overrated.lol", text = "My React Superweb"}},
    { medium = {href = "https://medium.com/@giovanni.dejan", text = "Medium Blog"} },
    { linkedin = "https://id.linkedin.com/in/iamdejan" },
    { github = "https://github.com/iamdejan" }
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.135.0"
